### ISSUE TITLE
Setting for CoreXY?

### ISSUE THREAD

**Issue by marshr32** [SourceRabbit/RabbitGRBL#1]
Hi, with normal GRBL I'd edit the config.h fore to enable CoreXY mode but in RabbitGRBL I can't find the setting anywhere.

Could you point me in the right direction please?

Also, will the backlash compensation work in a CoreXY machine?
ie is it looking at change of direction of the axis, or actually the motor?

Thanks.

**Comment by nsiatras** [comment]
@marshr32 I think you can use the following code implemented in the Grbl_Esp32 project
https://github.com/bdring/Grbl_Esp32/blob/main/Grbl_Esp32/Custom/CoreXY.cpp

It is a CoreXY machine definition.
Let me know if you try it and need further assistance
