### ISSUE TITLE
Feed hold, resume and stop switch inputs

### ISSUE THREAD

**Issue by mparkerlisberg** [SourceRabbit/RabbitGRBL#2]
Is it possible to use:
#define CONTROL_FEED_HOLD_PIN   GPIO_NUM_XX
#define CONTROL_CYCLE_START_PIN    GPIO_NUM_XX
#define CONTROL_RESET_PIN      GPIO_NUM_XX
in the machine definition file to add switch inputs as it is done in GrblESP32 or is it more complicated than this.

Malcolm

**Comment by nsiatras** [comment]
@mparkerlisberg Never tested it but I believe you can. The pin definitions are ready in the code

**Comment by mparkerlisberg** [comment]
Thank you so much.  You saved me hours of going through the code in all those files.  I will report on the trial, but it will be a while before I do as I have to finish the stepper drive box first and test it all on an Arduino Nano GRBL.  I did get Rabbit Gcode Sender running on Windows 10, with some help from my son, as I go back to Fortran, Algol and Pascal code days.  It ran once and then did not run again.  The path was not set in Windows.

Malcolm

**Comment by nsiatras** [comment]
@mparkerlisberg Thank you for your feedback. You can always download and try Focus. Our new multi-axis grbl control software.
https://www.sourcerabbit.com/Shop/pr-i-91-t-focus-cnc-control-software.htm
